// <auto-generated />
using System;
using CourseLibrary.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseLibrary.API.Migrations
{
    [DbContext(typeof(CourseLibraryContext))]
    [Migration("20260307094106_SeedCourses")]
    partial class SeedCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("CourseLibrary.API.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DateOfBirth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            DateOfBirth = 1279360106496000180L,
                            FirstName = "Berry",
                            LastName = "Griffin Beak Eldritch",
                            MainCategory = "Ships"
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            DateOfBirth = 1277955145728000180L,
                            FirstName = "Nancy",
                            LastName = "Swashbuckler Rye",
                            MainCategory = "Rum"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            DateOfBirth = 1264753115136000120L,
                            FirstName = "Eli",
                            LastName = "Ivory Bones Sweet",
                            MainCategory = "Singing"
                        },
                        new
                        {
                            Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            DateOfBirth = 1264248815616000120L,
                            FirstName = "Arnold",
                            LastName = "The Unseen Stafford",
                            MainCategory = "Singing"
                        },
                        new
                        {
                            Id = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            DateOfBirth = 1264066560000000120L,
                            FirstName = "Seabury",
                            LastName = "Toxic Reyson",
                            MainCategory = "Maps"
                        },
                        new
                        {
                            Id = new Guid("2aadd2df-7caf-45ab-9355-7f6332985a87"),
                            DateOfBirth = 1279813091328000120L,
                            FirstName = "Rutherford",
                            LastName = "Fearless Cloven",
                            MainCategory = "General debauchery"
                        },
                        new
                        {
                            Id = new Guid("2ee49fe3-edf2-4f91-8409-3eb25ce6ca51"),
                            DateOfBirth = 1280793378816000120L,
                            FirstName = "Atherton",
                            LastName = "Crow Ridley",
                            MainCategory = "Rum"
                        });
                });

            modelBuilder.Entity("CourseLibrary.API.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f1b8c0-6c71-4c75-9f3c-9a6c7d2e1111"),
                            AuthorId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "Every pirate needs to know how to swing a sword without losing a finger. In this course you'll learn the basics of sword fighting and how to look intimidating while doing it.",
                            Title = "Sword Fighting for Beginners"
                        },
                        new
                        {
                            Id = new Guid("b7d4f20c-89b4-41c3-92af-1e8a3d7e2222"),
                            AuthorId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Description = "Not all X's mark the spot. Learn how to read treasure maps, decipher pirate symbols, and avoid digging holes in the wrong places.",
                            Title = "Treasure Map Reading 101"
                        },
                        new
                        {
                            Id = new Guid("c8a73f95-02c4-4d16-9a9b-3f4b5e9a3333"),
                            AuthorId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Description = "A good pirate listens to their parrot. In this course you'll learn how to understand, train, and occasionally negotiate with your feathered companion.",
                            Title = "Advanced Parrot Communication"
                        },
                        new
                        {
                            Id = new Guid("d91f3c62-8e1a-4a70-b9b7-7c2d6a1b4444"),
                            AuthorId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "Storms can sink ships and spirits alike. Learn the techniques pirates use to survive raging seas and keep their treasure dry.",
                            Title = "Storm Navigation Mastery"
                        },
                        new
                        {
                            Id = new Guid("e24a7d80-ff5e-4e63-8e57-5a8d0c2c5555"),
                            AuthorId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Description = "Burying treasure is easy. Remembering where you buried it is harder. This course covers proper treasure storage, secrecy, and retrieval strategies.",
                            Title = "Hidden Treasure Logistics"
                        },
                        new
                        {
                            Id = new Guid("f3b9c1de-22fa-4a0b-96e6-2d9e4f6f6666"),
                            AuthorId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Description = "Not every encounter needs to end in cannon fire. Learn how pirates negotiate, bluff, and occasionally walk away with more treasure than they started with.",
                            Title = "Pirate Negotiation Tactics"
                        },
                        new
                        {
                            Id = new Guid("10c5e7a1-1b44-4b68-83b8-9d1a2b3c7777"),
                            AuthorId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "Cannons are powerful tools of persuasion. This course teaches you how to load, aim, and fire cannons without accidentally sinking your own ship.",
                            Title = "Cannon Operation and Safety"
                        },
                        new
                        {
                            Id = new Guid("21d6f8b2-2c55-4c79-94c9-a2b3c4d58888"),
                            AuthorId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Description = "Some of the best pirate victories happen under the cover of darkness. Learn stealth boarding techniques and how to move quietly across a creaky deck.",
                            Title = "Night Raids and Silent Boarding"
                        },
                        new
                        {
                            Id = new Guid("32e709c3-3d66-4d8a-a5da-b3c4d5e69999"),
                            AuthorId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Description = "A pirate crew runs on rum. In this course you'll learn the basics of brewing, storing, and protecting your precious barrels from thirsty crewmates.",
                            Title = "Rum Brewing Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("43f81ad4-4e77-4e9b-b6eb-c4d5e6f7aaaa"),
                            AuthorId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "Sometimes things don't go according to plan. Learn essential survival skills for when you're stranded on a deserted island with nothing but a shovel and bad luck.",
                            Title = "Surviving on Deserted Islands"
                        });
                });

            modelBuilder.Entity("CourseLibrary.API.Entities.Course", b =>
                {
                    b.HasOne("CourseLibrary.API.Entities.Author", "Author")
                        .WithMany("Courses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CourseLibrary.API.Entities.Author", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
